/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package filmetela;

import filmedados.Filmes;
import filmesdao.FilmesDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class Filme extends javax.swing.JFrame {

    /**
     * Creates new form Filme
     */
    public Filme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblCenaflix = new javax.swing.JPanel();
        lblCenaflix = new javax.swing.JLabel();
        lblCadastro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        ftxtDatalancamento = new javax.swing.JFormattedTextField();
        txtCategoria = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblPesquise = new javax.swing.JLabel();
        txtIdPesquisar = new javax.swing.JTextField();
        btnIdPesquisar = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        lblPesquisar2 = new javax.swing.JLabel();
        txtIdPesquisaNome = new javax.swing.JTextField();
        btnPesquisarFilme = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFilmesCadast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCenaflix.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblCenaflix.setText("Cenaflix");

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCadastro.setText("Cadastro de Filmes");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setText("Nome do Filme:");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblData.setText("Data do Lançamento:");

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCategoria.setText("Categoria:");

        try {
            ftxtDatalancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnInserir.setText("Cadastrar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblPesquise.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesquise.setText("Pesquise o ID do Filme:");

        btnIdPesquisar.setText("Pesquisar");
        btnIdPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdPesquisarActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblID.setText("ID:");

        txtID.setEditable(false);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblPesquisar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPesquisar2.setText("Pesquise o nome do Filme:");

        btnPesquisarFilme.setText("Pesquisar");
        btnPesquisarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarFilmeActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(204, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFilmesCadast.setText("Listagem");
        btnFilmesCadast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmesCadastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tblCenaflixLayout = new javax.swing.GroupLayout(tblCenaflix);
        tblCenaflix.setLayout(tblCenaflixLayout);
        tblCenaflixLayout.setHorizontalGroup(
            tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblCenaflixLayout.createSequentialGroup()
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tblCenaflixLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblCadastro)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tblCenaflixLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar))
                    .addGroup(tblCenaflixLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblCenaflix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFilmesCadast)))
                .addContainerGap())
            .addGroup(tblCenaflixLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPesquisar2)
                    .addComponent(lblID)
                    .addComponent(lblPesquise)
                    .addComponent(lblNome)
                    .addComponent(lblData)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtDatalancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tblCenaflixLayout.createSequentialGroup()
                        .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdPesquisaNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtIdPesquisar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIdPesquisar)
                            .addComponent(btnPesquisarFilme))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        tblCenaflixLayout.setVerticalGroup(
            tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblCenaflixLayout.createSequentialGroup()
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCenaflix)
                    .addGroup(tblCenaflixLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFilmesCadast)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquise)
                    .addComponent(txtIdPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIdPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisar2)
                    .addComponent(txtIdPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftxtDatalancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria))
                .addGap(9, 9, 9)
                .addGroup(tblCenaflixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnLimpar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblCenaflix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblCenaflix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String nome = txtNome.getText();
        String categoria = txtCategoria.getText();
        String dataRecebida = ftxtDatalancamento.getText();
        SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");

        Filmes filme = new Filmes();

        filme.setNome(nome);
        filme.setCategoria(categoria);

        try {
            java.util.Date dataConvertida = conversor.parse(dataRecebida);
            java.sql.Date sqlDate = new java.sql.Date(dataConvertida.getTime());
            filme.setDatalancamento(sqlDate);
        } catch (ParseException ex) {

            System.out.println("Erro na conversão de data!" + ex.getMessage());
        }

        FilmesDAO filmesDAO = new FilmesDAO();
        filmesDAO.Inserir(filme);

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        ftxtDatalancamento.setText("");
        txtCategoria.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnIdPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdPesquisarActionPerformed
        int idPesquisa = Integer.parseInt(txtIdPesquisar.getText());

        FilmesDAO filmesDAO = new FilmesDAO();
        Filmes filme = filmesDAO.getFilmesById(idPesquisa);
        if (filme == null) {
            JOptionPane.showMessageDialog(this, "Filme não encontrado!");
        } else {
            txtID.setText(String.valueOf(filme.getId()));
            txtNome.setText(filme.getNome());
            txtCategoria.setText(filme.getCategoria());
        }
    }//GEN-LAST:event_btnIdPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int id = Integer.parseInt(txtIdPesquisar.getText());
        String nome = txtNome.getText();
        String categoria = txtCategoria.getText();
        String dataRecebida = ftxtDatalancamento.getText();
        SimpleDateFormat conversor = new SimpleDateFormat("dd/MM/yyyy");

        Filmes filme = new Filmes();
        filme.setId(id);
        filme.setNome(nome);
        filme.setCategoria(categoria);
        try {
            java.util.Date dataConvertida = conversor.parse(dataRecebida);
            java.sql.Date sqlDate = new java.sql.Date(dataConvertida.getTime());
            filme.setDatalancamento(sqlDate);
        } catch (ParseException ex) {

            System.out.println("Erro na conversão de data!" + ex.getMessage());
        }

        FilmesDAO filmesDAO = new FilmesDAO();
        filmesDAO.Editar(filme);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarFilmeActionPerformed
        String nomepesquisa = txtIdPesquisaNome.getText();

        FilmesDAO filmesDAO = new FilmesDAO();
        Filmes filme = filmesDAO.getFilmesByNome(nomepesquisa);

        if (filme == null) {
            JOptionPane.showMessageDialog(this, "Filme não encontrado!");
        } else {
            txtID.setText(String.valueOf(filme.getId()));
            txtNome.setText(filme.getNome());
            txtCategoria.setText(filme.getCategoria());
        }
    }//GEN-LAST:event_btnPesquisarFilmeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(txtID.getText());

        FilmesDAO filmesDAO = new FilmesDAO();
        filmesDAO.Excluir(id);

        txtID.setText("");
        txtNome.setText("");
        ftxtDatalancamento.setText("");
        txtCategoria.setText("");
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFilmesCadastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmesCadastActionPerformed
        ListaFilme fre = new ListaFilme();
        fre.setVisible(true);
    }//GEN-LAST:event_btnFilmesCadastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFilmesCadast;
    private javax.swing.JButton btnIdPesquisar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarFilme;
    private javax.swing.JFormattedTextField ftxtDatalancamento;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCenaflix;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisar2;
    private javax.swing.JLabel lblPesquise;
    private javax.swing.JPanel tblCenaflix;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdPesquisaNome;
    private javax.swing.JTextField txtIdPesquisar;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
